-- AstroVip Forum
--
-- Acest fișier vechi de bootstrap a fost retras la 17 septembrie 2026 deoarece
-- nu mai corespundea tabelelor folosite de clientul web. Schema activă este
-- administrată prin migrații Supabase. Nu rula un bootstrap istoric peste
-- proiectul de producție.
--
-- Cea mai nouă migrație verificată:
--   migrations/202609170001_harden_forum_permissions_and_moderation.sql
