-- AstroVip Forum MVP — PostgreSQL / Supabase
-- Rulează acest script în SQL Editor într-un proiect Supabase nou.

create extension if not exists pgcrypto;

create table if not exists public.forum_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Membru AstroVip',
  role text not null default 'member' check (role in ('member','moderator','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.forum_categories (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  description text,
  icon text default '✦',
  position int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.forum_topics (
  id uuid primary key default gen_random_uuid(),
  category_id bigint not null references public.forum_categories(id) on delete restrict,
  author_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  title text not null check (char_length(title) between 3 and 140),
  body text not null check (char_length(body) between 3 and 6000),
  status text not null default 'open' check (status in ('open','locked','hidden')),
  is_pinned boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.forum_replies (
  id uuid primary key default gen_random_uuid(),
  topic_id uuid not null references public.forum_topics(id) on delete cascade,
  author_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  body text not null check (char_length(body) between 1 and 4000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.forum_reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references auth.users(id) on delete cascade,
  topic_id uuid references public.forum_topics(id) on delete cascade,
  reply_id uuid references public.forum_replies(id) on delete cascade,
  reason text not null check (char_length(reason) between 3 and 500),
  status text not null default 'open' check (status in ('open','reviewed','closed')),
  created_at timestamptz not null default now(),
  check ((topic_id is not null) <> (reply_id is not null))
);

create or replace function public.forum_is_staff(uid uuid)
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.forum_profiles where id=uid and role in ('moderator','admin'));
$$;

create or replace function public.forum_touch_topic()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  update public.forum_topics set updated_at=now() where id=new.topic_id;
  return new;
end; $$;

drop trigger if exists forum_reply_touch_topic on public.forum_replies;
create trigger forum_reply_touch_topic after insert on public.forum_replies for each row execute function public.forum_touch_topic();

create or replace function public.forum_handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.forum_profiles(id,display_name)
  values(new.id,coalesce(nullif(new.raw_user_meta_data->>'display_name',''),split_part(new.email,'@',1),'Membru AstroVip'))
  on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists forum_new_user on auth.users;
create trigger forum_new_user after insert on auth.users for each row execute function public.forum_handle_new_user();

alter table public.forum_profiles enable row level security;
alter table public.forum_categories enable row level security;
alter table public.forum_topics enable row level security;
alter table public.forum_replies enable row level security;
alter table public.forum_reports enable row level security;

create policy "profiles public read" on public.forum_profiles for select using (true);
create policy "profile owner update" on public.forum_profiles for update using (auth.uid()=id) with check (auth.uid()=id and role='member');
create policy "categories public read" on public.forum_categories for select using (true);
create policy "categories staff write" on public.forum_categories for all using (public.forum_is_staff(auth.uid())) with check (public.forum_is_staff(auth.uid()));
create policy "topics public read" on public.forum_topics for select using (status <> 'hidden' or public.forum_is_staff(auth.uid()));
create policy "topics authenticated insert" on public.forum_topics for insert to authenticated with check (auth.uid()=author_id);
create policy "topics owner or staff update" on public.forum_topics for update to authenticated using (auth.uid()=author_id or public.forum_is_staff(auth.uid())) with check (auth.uid()=author_id or public.forum_is_staff(auth.uid()));
create policy "topics owner or staff delete" on public.forum_topics for delete to authenticated using (auth.uid()=author_id or public.forum_is_staff(auth.uid()));
create policy "replies public read" on public.forum_replies for select using (true);
create policy "replies authenticated insert" on public.forum_replies for insert to authenticated with check (auth.uid()=author_id);
create policy "replies owner or staff update" on public.forum_replies for update to authenticated using (auth.uid()=author_id or public.forum_is_staff(auth.uid())) with check (auth.uid()=author_id or public.forum_is_staff(auth.uid()));
create policy "replies owner or staff delete" on public.forum_replies for delete to authenticated using (auth.uid()=author_id or public.forum_is_staff(auth.uid()));
create policy "reports own insert" on public.forum_reports for insert to authenticated with check (auth.uid()=reporter_id);
create policy "reports staff read" on public.forum_reports for select to authenticated using (public.forum_is_staff(auth.uid()));
create policy "reports staff update" on public.forum_reports for update to authenticated using (public.forum_is_staff(auth.uid())) with check (public.forum_is_staff(auth.uid()));

insert into public.forum_categories(slug,name,description,icon,position) values
('astrologie-natala','Astrologie natală','Planete, case, aspecte și axe','✦',1),
('previziuni-timing','Previziuni & timing','Tranzite, arce solare și progresii','◷',2),
('relatii-sinastrie','Relații & sinastrie','Compatibilitate și dinamici de cuplu','♡',3),
('relocare-local-space','Relocare & Local Space','Astrocartografie și hărți relocate','⌖',4),
('numerologie','Numerologie','Nume, date și cicluri numerice','#',5),
('intrebari-generale','Întrebări generale','Discuții despre astrologie','?',6)
on conflict (slug) do nothing;

create index if not exists forum_topics_category_idx on public.forum_topics(category_id,updated_at desc);
create index if not exists forum_topics_updated_idx on public.forum_topics(updated_at desc);
create index if not exists forum_replies_topic_idx on public.forum_replies(topic_id,created_at);
