(() => {
'use strict';
const cfg=window.ASTROVIP_FORUM_CONFIG||{};
const hasBackend=Boolean(cfg.url&&cfg.anonKey&&window.supabase);
const db=hasBackend?window.supabase.createClient(cfg.url,cfg.anonKey):null;
const $=s=>document.querySelector(s);
const els={statusDot:$('#statusDot'),statusTitle:$('#statusTitle'),statusText:$('#statusText'),demoNotice:$('#demoNotice'),categoryList:$('#categoryList'),topicList:$('#topicList'),topicHeading:$('#topicHeading'),topicCategory:$('#topicCategory'),statCategories:$('#statCategories'),statTopics:$('#statTopics'),statReplies:$('#statReplies'),statMembers:$('#statMembers'),authBtn:$('#authBtn'),authModal:$('#authModal'),authForm:$('#authForm'),authMsg:$('#authMsg'),displayName:$('#displayName'),notificationBtn:$('#notificationBtn'),notificationBadge:$('#notificationBadge'),notificationsModal:$('#notificationsModal'),notificationList:$('#notificationList'),markReadBtn:$('#markReadBtn'),memberCard:$('#memberCard'),topicModal:$('#topicModal'),topicForm:$('#topicForm'),topicMsg:$('#topicMsg'),threadModal:$('#threadModal'),threadContent:$('#threadContent'),replyForm:$('#replyForm'),replyBody:$('#replyBody'),replyMsg:$('#replyMsg'),searchInput:$('#searchInput'),sortSelect:$('#sortSelect'),pagination:$('#pagination'),prevPage:$('#prevPage'),nextPage:$('#nextPage'),pageInfo:$('#pageInfo'),profileModal:$('#profileModal'),profileForm:$('#profileForm'),profileMsg:$('#profileMsg'),profileDisplayName:$('#profileDisplayName'),profileUsername:$('#profileUsername'),profileBio:$('#profileBio'),profileWebsite:$('#profileWebsite'),profileAvatar:$('#profileAvatar'),profileAvatarPreview:$('#profileAvatarPreview'),adminSection:$('#adminSection'),roleForm:$('#roleForm'),roleUsername:$('#roleUsername'),roleSelect:$('#roleSelect'),roleMsg:$('#roleMsg'),signOutBtn:$('#signOutBtn'),publicProfileModal:$('#publicProfileModal'),publicProfileContent:$('#publicProfileContent'),editModal:$('#editModal'),editForm:$('#editForm'),editTitleWrap:$('#editTitleWrap'),editTitle:$('#editTitle'),editBody:$('#editBody'),editMsg:$('#editMsg'),toast:$('#toast')};
const categoriesFallback=[{id:'natal',name:'Astrologie natală',description:'Planete, case, aspecte și axe',icon:'✦'},{id:'timing',name:'Previziuni & timing',description:'Tranzite, arce solare și progresii',icon:'◷'},{id:'sinastrie',name:'Relații & sinastrie',description:'Compatibilitate și dinamici de cuplu',icon:'♡'},{id:'relocare',name:'Relocare & Local Space',description:'Astrocartografie și hărți relocate',icon:'⌖'},{id:'numerologie',name:'Numerologie',description:'Nume, date și cicluri numerice',icon:'#'},{id:'general',name:'Întrebări generale',description:'Discuții despre astrologie',icon:'?'}];
let categories=[],topics=[],profiles=new Map(),reactionRows=[],selectedCategory=null,currentTopic=null,currentUser=null,currentProfile=null,authMode='login',page=1,perPage=12,editTarget=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmt=v=>{if(!v)return'acum';try{return new Intl.DateTimeFormat('ro-RO',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch{return''}};
const initials=v=>(v||'A').trim().slice(0,1).toUpperCase();
const openModal=el=>{if(el){el.classList.add('open');el.setAttribute('aria-hidden','false')}};
const closeModal=el=>{if(el){el.classList.remove('open');el.setAttribute('aria-hidden','true')}};
const toast=m=>{els.toast.textContent=m;els.toast.classList.add('show');clearTimeout(window.__forumToast);window.__forumToast=setTimeout(()=>els.toast.classList.remove('show'),2600)};
const staff=()=>['moderator','admin'].includes(currentProfile?.role);
const admin=()=>currentProfile?.role==='admin';
const profileFor=id=>profiles.get(String(id))||null;
const displayFor=(id,fallback)=>profileFor(id)?.display_name||profileFor(id)?.username||fallback||'Membru AstroVip';
function avatarHtml(id,fallback,large=false){const p=profileFor(id),name=p?.display_name||p?.username||fallback||'A',cls=large?'profile-avatar-preview':'avatar';return p?.avatar_url?`<span class="${cls}"><img src="${esc(p.avatar_url)}" alt=""></span>`:`<span class="${cls}">${esc(initials(name))}</span>`}
function roleBadge(id){const r=profileFor(id)?.role;if(!r||r==='member')return'';return`<span class="role-badge">${r==='admin'?'Administrator':'Moderator'}</span>`}
function safeWebsite(v){return /^https?:\/\//i.test(v||'')?v:''}
function countReactions(kind,id,type){return reactionRows.filter(r=>String(r[kind+'_id'])===String(id)&&r.reaction_type===type).length}
function hasReaction(kind,id,type){return Boolean(currentUser&&reactionRows.some(r=>r.user_id===currentUser.id&&String(r[kind+'_id'])===String(id)&&r.reaction_type===type))}
function reactionButtons(kind,id){return['like','helpful','insightful'].map(type=>{const label={like:'♥ Apreciez',helpful:'✓ Util',insightful:'✦ Insight'}[type];return`<button type="button" class="reaction-btn ${hasReaction(kind,id,type)?'active':''}" data-react-kind="${kind}" data-react-id="${esc(id)}" data-react-type="${type}">${label} <span>${countReactions(kind,id,type)}</span></button>`}).join('')}

async function init(){
  if(!hasBackend){els.statusTitle.textContent='Forum indisponibil';els.statusText.textContent='Configurația bazei de date lipsește';els.demoNotice.hidden=false;categories=categoriesFallback;renderAll();return}
  els.statusDot.classList.add('online');els.statusTitle.textContent='Forum online';els.statusText.textContent='Postările sunt sincronizate public';
  const{data:{session}}=await db.auth.getSession();await syncUser(session);
  db.auth.onAuthStateChange((_event,s)=>setTimeout(()=>syncUser(s),0));
  await loadRemote();
}
async function syncUser(session){currentUser=session?.user||null;currentProfile=null;if(currentUser){const{data}=await db.from('profiles').select('*').eq('id',currentUser.id).maybeSingle();currentProfile=data||null}updateAuthUI();await loadNotifications();renderMemberCard()}
async function loadRemote(){
  const[catRes,topicRes,profileRes,replyRes,reactionRes]=await Promise.all([
    db.from('forum_categories').select('*').eq('is_active',true).order('position'),
    db.from('forum_topics').select('*').order('is_pinned',{ascending:false}).order('updated_at',{ascending:false}),
    db.from('profiles').select('id,username,display_name,avatar_url,bio,role,website,created_at'),
    db.from('forum_replies').select('topic_id'),
    db.from('forum_reactions').select('*')
  ]);
  if(catRes.error||topicRes.error){els.statusDot.classList.remove('online');els.statusTitle.textContent='Conexiune indisponibilă';els.statusText.textContent='Reîncarcă pagina';categories=categoriesFallback;topics=[];renderAll();return}
  categories=catRes.data||[];profiles=new Map((profileRes.data||[]).map(p=>[String(p.id),p]));reactionRows=reactionRes.data||[];
  const counts={};(replyRes.data||[]).forEach(r=>counts[r.topic_id]=(counts[r.topic_id]||0)+1);
  topics=(topicRes.data||[]).map(t=>({...t,reply_count:counts[t.id]||0}));els.statMembers.textContent=profiles.size;renderAll();renderMemberCard();
}
function renderAll(){renderCategories();renderTopics();renderStats();fillCategorySelect()}
function renderStats(){els.statCategories.textContent=categories.length;els.statTopics.textContent=topics.filter(t=>t.status==='open').length;els.statReplies.textContent=topics.reduce((n,t)=>n+(t.reply_count||0),0)}
function fillCategorySelect(){els.topicCategory.innerHTML='<option value="">Alege categoria</option>'+categories.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}
function renderCategories(){
  const counts={};topics.filter(t=>t.status==='open').forEach(t=>counts[t.category_id]=(counts[t.category_id]||0)+1);
  els.categoryList.innerHTML=`<button class="category ${selectedCategory===null?'active':''}" data-category=""><span class="cat-icon">◎</span><span><strong>Toate discuțiile</strong><small>Activitatea comunității</small></span><span class="count">${topics.filter(t=>t.status==='open').length}</span></button>`+categories.map(c=>`<button class="category ${String(selectedCategory)===String(c.id)?'active':''}" data-category="${esc(c.id)}"><span class="cat-icon">${esc(c.icon||'✦')}</span><span><strong>${esc(c.name)}</strong><small>${esc(c.description||'')}</small></span><span class="count">${counts[c.id]||0}</span></button>`).join('');
  els.categoryList.querySelectorAll('.category').forEach(btn=>btn.addEventListener('click',()=>{selectedCategory=btn.dataset.category||null;page=1;const c=categories.find(x=>String(x.id)===String(selectedCategory));els.topicHeading.textContent=c?c.name:'Discuții recente';renderAll();document.querySelector('#discutii').scrollIntoView({behavior:'smooth'})}));
}
function filteredTopics(){let list=topics.filter(t=>t.status==='open'||staff());if(selectedCategory)list=list.filter(t=>String(t.category_id)===String(selectedCategory));const q=els.searchInput.value.trim().toLowerCase();if(q)list=list.filter(t=>(`${t.title} ${t.body}`).toLowerCase().includes(q));if(els.sortSelect.value==='replies')list.sort((a,b)=>(b.reply_count||0)-(a.reply_count||0));else list.sort((a,b)=>(Number(b.is_pinned)-Number(a.is_pinned))||(new Date(b.updated_at)-new Date(a.updated_at)));return list}
function renderTopics(){
  const all=filteredTopics(),pages=Math.max(1,Math.ceil(all.length/perPage));if(page>pages)page=pages;const start=(page-1)*perPage,list=all.slice(start,start+perPage);
  if(!list.length)els.topicList.innerHTML='<div class="empty">Nu există încă discuții aici. Deschide primul subiect.</div>';
  else els.topicList.innerHTML=list.map(t=>{const c=categories.find(x=>String(x.id)===String(t.category_id)),author=displayFor(t.author_id,t.author_name),chips=`${t.is_locked?'<span class="status-chip">🔒 închis</span>':''}${t.status!=='open'?'<span class="status-chip">ascuns</span>':''}`;return`<article class="topic-row" data-topic="${esc(t.id)}">${avatarHtml(t.author_id,author)}<div><div class="topic-title">${t.is_pinned?'📌 ':''}${esc(t.title)} ${chips}</div><div class="topic-meta">${esc(c?.name||'General')} · <span class="profile-link" data-profile="${esc(t.author_id)}">${esc(author)}</span> ${roleBadge(t.author_id)} · ${fmt(t.created_at)}</div></div><div class="topic-count"><strong>${t.reply_count||0}</strong><small>răspunsuri</small></div><div class="last"><small>Actualizat</small><br>${fmt(t.updated_at||t.created_at)}</div></article>`}).join('');
  els.topicList.querySelectorAll('.topic-row').forEach(row=>row.addEventListener('click',e=>{if(e.target.closest('[data-profile]'))return;openThread(row.dataset.topic)}));bindProfileLinks(els.topicList);
  els.pageInfo.textContent=`Pagina ${page} / ${pages}`;els.prevPage.disabled=page<=1;els.nextPage.disabled=page>=pages;els.pagination.hidden=all.length<=perPage;
}
function renderMemberCard(){
  if(!currentUser){els.memberCard.innerHTML='<p>Autentifică-te pentru profil, notificări și publicare.</p><button class="btn ghost full" type="button" data-login>Autentificare</button>';els.memberCard.querySelector('[data-login]')?.addEventListener('click',()=>openModal(els.authModal));return}
  const name=currentProfile?.display_name||currentProfile?.username||currentUser.email?.split('@')[0]||'Membru';els.memberCard.innerHTML=`<div class="mini-profile">${avatarHtml(currentUser.id,name)}<div class="mini-profile-text"><strong>${esc(name)}</strong><small>@${esc(currentProfile?.username||'profil')}</small>${roleBadge(currentUser.id)}</div></div><button class="btn ghost full compact" type="button" data-open-profile style="margin-top:14px">Editează profilul</button>`;els.memberCard.querySelector('[data-open-profile]')?.addEventListener('click',openOwnProfile);
}
function updateAuthUI(){els.authBtn.textContent=currentUser?'Contul meu':'Autentificare';els.notificationBtn.hidden=!currentUser}
function bindProfileLinks(root=document){root.querySelectorAll('[data-profile]').forEach(el=>el.addEventListener('click',e=>{e.stopPropagation();openPublicProfile(el.dataset.profile)}))}
async function openPublicProfile(id){const p=profileFor(id);if(!p)return;const name=p.display_name||p.username||'Membru AstroVip',web=safeWebsite(p.website);els.publicProfileContent.innerHTML=`<div class="public-profile">${avatarHtml(p.id,name,true)}<span class="kicker">Profil public</span><h2>${esc(name)}</h2><div>@${esc(p.username||'membru')} ${roleBadge(p.id)}</div><p>${esc(p.bio||'Acest membru nu a adăugat încă o descriere.')}</p>${web?`<a href="${esc(web)}" target="_blank" rel="noopener noreferrer">Website</a>`:''}<p><small>Membru din ${fmt(p.created_at)}</small></p></div>`;openModal(els.publicProfileModal)}

async function openThread(id){
  currentTopic=topics.find(t=>String(t.id)===String(id));if(!currentTopic)return;
  const{data:replies,error}=await db.from('forum_replies').select('*').eq('topic_id',id).order('created_at');if(error){toast(error.message);return}const rows=replies||[];
  const author=displayFor(currentTopic.author_id,currentTopic.author_name),owner=currentUser?.id===currentTopic.author_id;
  const topicActions=(owner||staff())?`<div class="post-actions">${owner?'<button class="action-btn" type="button" data-edit-topic>Editează</button>':''}<button class="action-btn danger-link" type="button" data-delete-topic>Șterge</button>${staff()?`<button class="action-btn" type="button" data-pin-topic>${currentTopic.is_pinned?'Scoate fixarea':'Fixează'}</button><button class="action-btn" type="button" data-lock-topic>${currentTopic.is_locked?'Deblochează':'Blochează'}</button><button class="action-btn" type="button" data-hide-topic>${currentTopic.status==='open'?'Ascunde':'Publică'}</button>`:''}</div>`:'';
  els.threadContent.innerHTML=`<div class="thread-head"><span class="kicker">${esc(categories.find(c=>String(c.id)===String(currentTopic.category_id))?.name||'Forum')}</span><h2 id="threadTitle">${esc(currentTopic.title)}</h2><div class="thread-meta"><span class="profile-link" data-profile="${esc(currentTopic.author_id)}">${esc(author)}</span> ${roleBadge(currentTopic.author_id)} · ${fmt(currentTopic.created_at)}</div></div><div class="post-shell"><div class="post-top"><div class="post-author">${avatarHtml(currentTopic.author_id,author)}<strong>${esc(author)}</strong></div>${topicActions}</div><div class="post-body">${esc(currentTopic.body)}</div><div class="reaction-row">${reactionButtons('topic',currentTopic.id)}</div></div><div class="replies"><h3>Răspunsuri (${rows.length})</h3>${rows.length?rows.map(renderReply).join(''):'<div class="empty">Niciun răspuns încă.</div>'}</div>`;
  bindProfileLinks(els.threadContent);bindThreadActions();
  const locked=currentTopic.is_locked&&!staff();els.replyForm.classList.toggle('locked',locked);els.replyBody.disabled=locked;els.replyForm.querySelector('button[type="submit"]').disabled=locked;els.replyBody.placeholder=locked?'Subiectul este închis pentru răspunsuri.':'Scrie un răspuns…';openModal(els.threadModal);
}
function renderReply(r){const author=displayFor(r.author_id,r.author_name),owner=currentUser?.id===r.author_id,actions=(owner||staff())?`<div class="post-actions">${owner?`<button class="action-btn" type="button" data-edit-reply="${esc(r.id)}">Editează</button>`:''}<button class="action-btn danger-link" type="button" data-delete-reply="${esc(r.id)}">Șterge</button>${staff()?`<button class="action-btn" type="button" data-hide-reply="${esc(r.id)}" data-hidden="${r.is_hidden?'1':'0'}">${r.is_hidden?'Afișează':'Ascunde'}</button>`:''}</div>`:'';return`<div class="reply ${r.is_hidden?'hidden-post':''}" data-reply="${esc(r.id)}"><div class="post-top"><div class="post-author">${avatarHtml(r.author_id,author)}<div><strong class="profile-link" data-profile="${esc(r.author_id)}">${esc(author)}</strong> ${roleBadge(r.author_id)}<br><small>${fmt(r.created_at)}${r.is_hidden?' · ascuns':''}</small></div></div>${actions}</div><p>${esc(r.body)}</p><div class="reaction-row">${reactionButtons('reply',r.id)}</div></div>`}
function bindThreadActions(){
  els.threadContent.querySelectorAll('[data-react-kind]').forEach(b=>b.addEventListener('click',()=>toggleReaction(b.dataset.reactKind,b.dataset.reactId,b.dataset.reactType)));
  els.threadContent.querySelector('[data-edit-topic]')?.addEventListener('click',()=>openEdit('topic',currentTopic));
  els.threadContent.querySelector('[data-delete-topic]')?.addEventListener('click',deleteTopic);
  els.threadContent.querySelector('[data-pin-topic]')?.addEventListener('click',()=>moderateTopic({is_pinned:!currentTopic.is_pinned}));
  els.threadContent.querySelector('[data-lock-topic]')?.addEventListener('click',()=>moderateTopic({is_locked:!currentTopic.is_locked}));
  els.threadContent.querySelector('[data-hide-topic]')?.addEventListener('click',()=>moderateTopic({status:currentTopic.status==='open'?'hidden':'open'}));
  els.threadContent.querySelectorAll('[data-edit-reply]').forEach(b=>b.addEventListener('click',()=>{const el=b.closest('.reply');openEdit('reply',{id:b.dataset.editReply,body:el.querySelector('p').textContent})}));
  els.threadContent.querySelectorAll('[data-delete-reply]').forEach(b=>b.addEventListener('click',()=>deleteReply(b.dataset.deleteReply)));
  els.threadContent.querySelectorAll('[data-hide-reply]').forEach(b=>b.addEventListener('click',()=>moderateReply(b.dataset.hideReply,b.dataset.hidden!=='1')));
}
async function toggleReaction(kind,id,type){if(!currentUser){closeModal(els.threadModal);openModal(els.authModal);toast('Autentifică-te pentru a reacționa.');return}const existing=reactionRows.find(r=>r.user_id===currentUser.id&&r.reaction_type===type&&String(r[kind+'_id'])===String(id));let error;if(existing)({error}=await db.from('forum_reactions').delete().eq('id',existing.id));else{const row={user_id:currentUser.id,reaction_type:type};row[kind+'_id']=id;({error}=await db.from('forum_reactions').insert(row))}if(error){toast(error.message);return}const topicId=currentTopic?.id;await loadRemote();if(topicId)await openThread(topicId)}
function openEdit(kind,obj){editTarget={kind,id:obj.id};els.editMsg.textContent='';els.editTitleWrap.hidden=kind!=='topic';els.editTitle.value=kind==='topic'?obj.title:'';els.editBody.value=obj.body||'';openModal(els.editModal)}
async function deleteTopic(){if(!confirm('Ștergi acest subiect și toate răspunsurile?'))return;const id=currentTopic.id,{error}=await db.from('forum_topics').delete().eq('id',id);if(error){toast(error.message);return}closeModal(els.threadModal);currentTopic=null;await loadRemote();toast('Subiect șters.')}
async function deleteReply(id){if(!confirm('Ștergi acest răspuns?'))return;const topicId=currentTopic.id,{error}=await db.from('forum_replies').delete().eq('id',id);if(error){toast(error.message);return}await loadRemote();await openThread(topicId);toast('Răspuns șters.')}
async function moderateTopic(patch){const id=currentTopic.id,{error}=await db.from('forum_topics').update(patch).eq('id',id);if(error){toast(error.message);return}await loadRemote();currentTopic=topics.find(t=>String(t.id)===String(id))||currentTopic;await openThread(id)}
async function moderateReply(id,hide){const topicId=currentTopic.id,{error}=await db.from('forum_replies').update({is_hidden:hide}).eq('id',id);if(error){toast(error.message);return}await openThread(topicId)}

async function loadNotifications(){if(!currentUser){els.notificationBadge.hidden=true;return}const{data,error}=await db.from('forum_notifications').select('*').order('created_at',{ascending:false}).limit(50);if(error)return;const rows=data||[],unread=rows.filter(n=>!n.read_at).length;els.notificationBadge.textContent=String(unread);els.notificationBadge.hidden=!unread;els.notificationList.innerHTML=rows.length?rows.map(n=>`<button class="notification ${n.read_at?'':'unread'}" type="button" data-notification-topic="${esc(n.topic_id||'')}">${esc(n.message)}<small>${fmt(n.created_at)}</small></button>`).join(''):'<div class="empty">Nu ai notificări.</div>';els.notificationList.querySelectorAll('[data-notification-topic]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.notificationTopic;if(id){closeModal(els.notificationsModal);openThread(id)}}))}
async function markNotificationsRead(){if(!currentUser)return;const{error}=await db.from('forum_notifications').update({read_at:new Date().toISOString()}).eq('user_id',currentUser.id).is('read_at',null);if(!error)await loadNotifications()}
function openOwnProfile(){if(!currentUser){openModal(els.authModal);return}const p=currentProfile||{};els.profileDisplayName.value=p.display_name||'';els.profileUsername.value=p.username||'';els.profileBio.value=p.bio||'';els.profileWebsite.value=p.website||'';els.profileAvatar.value='';els.profileAvatarPreview.innerHTML=p.avatar_url?`<img src="${esc(p.avatar_url)}" alt="">`:esc(initials(p.display_name||p.username||currentUser.email));els.profileMsg.textContent='';els.adminSection.hidden=!admin();openModal(els.profileModal)}
async function saveProfile(e){e.preventDefault();if(!currentUser)return;els.profileMsg.textContent='';let avatar_url=currentProfile?.avatar_url||null;const file=els.profileAvatar.files?.[0];if(file){if(file.size>2097152){els.profileMsg.textContent='Avatarul poate avea maximum 2 MB.';return}const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`${currentUser.id}/avatar-${Date.now()}.${ext}`;const up=await db.storage.from('forum-avatars').upload(path,file,{upsert:false});if(up.error){els.profileMsg.textContent=up.error.message;return}avatar_url=db.storage.from('forum-avatars').getPublicUrl(path).data.publicUrl}const username=els.profileUsername.value.trim().toLowerCase(),display_name=els.profileDisplayName.value.trim();if(!/^[a-z0-9_]{3,30}$/.test(username)){els.profileMsg.textContent='Username: 3–30 caractere, doar litere, cifre și _.';return}const{error}=await db.from('profiles').update({username,display_name:display_name||null,bio:els.profileBio.value.trim()||null,website:els.profileWebsite.value.trim()||null,avatar_url}).eq('id',currentUser.id);if(error){els.profileMsg.textContent=error.message;return}const{data}=await db.from('profiles').select('*').eq('id',currentUser.id).single();currentProfile=data;await loadRemote();openOwnProfile();els.profileMsg.textContent='Profil salvat.';toast('Profil actualizat.')}
async function changeRole(e){e.preventDefault();els.roleMsg.textContent='';if(!admin())return;const username=els.roleUsername.value.trim().toLowerCase();const{data:target,error:findError}=await db.from('profiles').select('id,username').eq('username',username).maybeSingle();if(findError||!target){els.roleMsg.textContent='Utilizatorul nu a fost găsit.';return}const{error}=await db.from('profiles').update({role:els.roleSelect.value}).eq('id',target.id);if(error){els.roleMsg.textContent=error.message;return}els.roleMsg.textContent='Rol actualizat.';await loadRemote()}
function requireUser(){if(!currentUser){openModal(els.authModal);toast('Autentifică-te pentru a publica.');return false}return true}
function startTopic(){if(!requireUser())return;els.topicMsg.textContent='';openModal(els.topicModal)}

$('#newTopicBtn').addEventListener('click',startTopic);$('#newTopicTop').addEventListener('click',startTopic);
els.searchInput.addEventListener('input',()=>{page=1;renderTopics()});els.sortSelect.addEventListener('change',()=>{page=1;renderTopics()});
els.prevPage.addEventListener('click',()=>{if(page>1){page--;renderTopics();document.querySelector('#discutii').scrollIntoView({behavior:'smooth'})}});
els.nextPage.addEventListener('click',()=>{page++;renderTopics();document.querySelector('#discutii').scrollIntoView({behavior:'smooth'})});
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(document.getElementById(b.dataset.close))));document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m)}));document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.modal.open').forEach(closeModal)});
els.authBtn.addEventListener('click',()=>currentUser?openOwnProfile():openModal(els.authModal));els.notificationBtn.addEventListener('click',async()=>{await loadNotifications();openModal(els.notificationsModal)});els.markReadBtn.addEventListener('click',markNotificationsRead);els.profileForm.addEventListener('submit',saveProfile);els.roleForm.addEventListener('submit',changeRole);els.signOutBtn.addEventListener('click',async()=>{await db.auth.signOut();closeModal(els.profileModal);toast('Ai ieșit din cont.')});
document.querySelectorAll('[data-auth-mode]').forEach(b=>b.addEventListener('click',()=>{authMode=b.dataset.authMode;document.querySelectorAll('[data-auth-mode]').forEach(x=>x.classList.toggle('active',x===b));els.displayName.hidden=authMode!=='signup';$('#authTitle').textContent=authMode==='signup'?'Creează cont':'Autentificare'}));
els.authForm.addEventListener('submit',async e=>{e.preventDefault();els.authMsg.textContent='';const email=$('#email').value.trim(),password=$('#password').value,name=els.displayName.value.trim();const username=(name||email.split('@')[0]).toLowerCase().replace(/[^a-z0-9_]/g,'').slice(0,30);const res=authMode==='signup'?await db.auth.signUp({email,password,options:{data:{display_name:name||email.split('@')[0],full_name:name||email.split('@')[0],username:username.length>=3?username:undefined}}}):await db.auth.signInWithPassword({email,password});if(res.error){els.authMsg.textContent=res.error.message;return}closeModal(els.authModal);e.target.reset();toast(authMode==='signup'?'Cont creat. Verifică emailul dacă este solicitat.':'Autentificare reușită.')});
els.topicForm.addEventListener('submit',async e=>{e.preventDefault();if(!requireUser())return;els.topicMsg.textContent='';const title=$('#topicTitle').value.trim(),body=$('#topicBody').value.trim(),category_id=els.topicCategory.value,author_name=currentProfile?.display_name||currentProfile?.username||currentUser.email?.split('@')[0]||'Membru AstroVip';const{error}=await db.from('forum_topics').insert({category_id,author_id:currentUser.id,author_name,title,body});if(error){els.topicMsg.textContent=error.message;return}e.target.reset();closeModal(els.topicModal);await loadRemote();toast('Subiect publicat.')});
els.replyForm.addEventListener('submit',async e=>{e.preventDefault();if(!currentTopic||!requireUser())return;const body=els.replyBody.value.trim();if(!body)return;const author_name=currentProfile?.display_name||currentProfile?.username||currentUser.email?.split('@')[0]||'Membru AstroVip';const topicId=currentTopic.id,{error}=await db.from('forum_replies').insert({topic_id:topicId,author_id:currentUser.id,author_name,body});if(error){els.replyMsg.textContent=error.message;return}els.replyBody.value='';await loadRemote();await openThread(topicId);toast('Răspuns publicat.')});
els.editForm.addEventListener('submit',async e=>{e.preventDefault();if(!editTarget)return;els.editMsg.textContent='';let res;if(editTarget.kind==='topic')res=await db.from('forum_topics').update({title:els.editTitle.value.trim(),body:els.editBody.value.trim()}).eq('id',editTarget.id);else res=await db.from('forum_replies').update({body:els.editBody.value.trim()}).eq('id',editTarget.id);if(res.error){els.editMsg.textContent=res.error.message;return}const topicId=currentTopic?.id;closeModal(els.editModal);await loadRemote();if(topicId)await openThread(topicId);toast('Modificările au fost salvate.')});
init();
})();
